plugins {
    id("java")
    id("java-library")
    id("maven-publish")
}

repositories {
    mavenCentral()
}

[compileJava , compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = 'p6-drawer'

dependencies {
    testImplementation(platform("org.junit:junit-bom:5.9.1"))
    testImplementation("org.junit.jupiter:junit-jupiter")

    api("$gdxCustomModule:gdx:$gdxCustomVersion")

    api 'com.twelvemonkeys.imageio:imageio-webp:3.11.0'
}

tasks.test {
    useJUnitPlatform()
}


publishing {
    publications {
        maven(MavenPublication) {
            groupId = "pama1234"
            artifactId = "libgdx.webp"
            version = "$pama1234PublishVersion"
//      from(components["java"])
            from components.java

                  pom {
                      name.set("libgdx-webp")
                      description.set("load webp on desktop")
                      url.set("https://github.com/pama1234/just-some-other-libgdx-game")
                      scm {
                          url.set("https://github.com/pama1234/just-some-other-libgdx-game")
                      }
                  }
        }
    }
    repositories {
        mavenLocal()
    }
}

//java {
//  sourceCompatibility = JavaVersion.VERSION_17
//  targetCompatibility = JavaVersion.VERSION_17
//}